Saikai-oyo/Saikai

- package-lock.json
- package.json
- src/components/App.js
- src/components/Dashboard/Dashboard.jsx
- src/components/Dashboard/index.js
- src/components/ForgotPassword/ForgotPassword.jsx
- src/components/ForgotPassword/index.js
- src/components/ForgotPassword/style.js
- src/components/Login/Login.jsx
- src/components/Login/index.js
- src/components/Login/style.js
- src/components/Profile/Profile.jsx
- src/components/Profile/index.js
- src/components/Profile/style.js
- src/components/Signup/Signup.jsx
- src/components/Signup/index.js
- src/components/Signup/style.js
- src/components/UpdateProfile/UpdateProfile.jsx
- src/components/UpdateProfile/index.js
- src/components/UpdateProfile/style.js
- src/components/index.js
- src/components/style.js
- src/config/firebase.js
- src/constants/PrivateRoute.jsx
- src/contexts/AuthContext.js
- src/contexts/GlobalStore.jsx
- src/index.js
Create login, register, forgot-password and update-password components.
All connect to firebase hosting.
#6
> Feat 1 login and register

- .storybook/preview.js
- package-lock.json
- package.json
- src/components/Dashboard/Dashboard.stories.jsx
- src/components/ForgotPassword/ForgotPassword.stories.jsx
- src/components/Login/Login.stories.jsx
- src/components/Profile/Profile.stories.jsx
- src/components/Signup/Signup.stories.jsx
- src/components/UpdateProfile/UpdateProfile.stories.jsx
Initial storybook setting and add all user components to stories files.
> Feat 2 add components to storybook

- src/components/Dashboard/Backdrop/ShowPosition/ShowPosition.jsx
> [refactor-4] style for responsive

- public/404.html
- public/index.html
- src/components/Dashboard/Navbar/Navbar.jsx
> [fix-4] change href value

- src/components/Dashboard/Backdrop/ShowPosition/ShowPosition.jsx
> [fix-5] fix status change bug

- public/index.html
- src/components/Dashboard/Backdrop/AddPosition/AddPosition.jsx
- src/components/Dashboard/Backdrop/ShowPosition/ShowPosition.jsx
- src/components/Dashboard/Backdrop/ShowPosition/style.css
- src/components/Dashboard/List/List.jsx
> Fix 6 modal size

- src/components/Dashboard/Navbar/Navbar.jsx
- src/components/Dashboard/Navbar/style.css
> [fix-7] fix responsive navbar view

- src/components/Dashboard/Backdrop/AddPosition/AddPosition.jsx
- src/components/Dashboard/Backdrop/ShowPosition/ShowPosition.jsx
- src/helpers/index.js
> [feat-6] added date to position (show & add).

- src/components/Auth/Login/Login.jsx
- src/components/Auth/Login/style.css
> [feat-7] add bg color to user demo details

- src/components/Dashboard/Backdrop/ShowPosition/ShowPosition.jsx
- src/components/Dashboard/List/List.jsx
Temporary disabled close modal by clicking on `esc` key & on the `backdrop`.
> Fix 8 modal wrong details

- src/components/Dashboard/Homepage/Homepage.jsx
> Fix 9 minor changes

- README.md
Hila & I done rewrite `readme.md` file.
> [feat-49] rewrite readme

- public/style.css
- src/components/Dashboard/List/List.jsx
- src/components/Dashboard/Navbar/Navbar.jsx
- src/components/Modals/AddPosition/AddPositionModal.jsx
- src/components/Modals/ViewPosition/ViewPositionModal.jsx
I added tooltip style and data attribute to each icon in the navbar
> [feat-62] add tooltip to icons

- src/components/Dashboard/List/List.jsx
- src/components/Modals/AddPosition/AddPositionModal.jsx
- src/contexts/UpdatedPositionContext.jsx
I removed the console logs from the code.
> [feat-71] remove the consoles

- package-lock.json
Fix vulnerabilities from 5183 to 83.
> [fix-76] fix vulnerabilities  to 86 from 5183

- src/components/Dashboard/List/List.jsx
- src/contexts/AuthContext.js
- src/contexts/MessagesContext.jsx
- src/hooks/useKanban.jsx
1. fixed header not showing messages when updated
2. Fixed columns order
3. Fixed typo in initial columns creation
> [Fix-92] messages not showing on list header

- src/assets/icons/goBack.svg
- src/assets/icons/index.js
- src/components/Dashboard/List/List.jsx
- src/components/Input/style.js
- src/components/Navbar/DashboardNav/DashboardNav.jsx
- src/components/Navbar/DashboardNav/style.css
- src/components/Navbar/GeneralNav/GeneralNav.jsx
- src/components/Navbar/GeneralNav/style.css
- src/components/User/UpdateProfile/UpdateProfile.jsx
- src/components/User/UpdateProfile/style.js
design the page to be mobile responsive
> Feat 57 responsive update password page

- .eslintrc.json
- .github/workflows/ci.yml
- .prettierrc
- package-lock.json
- package.json
Added:
- Prettier
- Eslint
- ci.yml
- husky
- lint-staged
> [Feat-100] add prettier

- src/components/Dashboard/List/style.js
- src/components/Modals/ViewPosition/ViewPositionModal.jsx
- src/styles/Global.style.css
> [bug-96] - no scroll container

- src/components/Navbar/GeneralNav/style.css
- src/components/User/Profile/Profile.jsx
- src/components/User/Profile/style.js
> [Feat-56] responsive profile page

- src/components/Dashboard/List/List.jsx
- src/components/Dashboard/List/style.js
- src/components/Modals/AddPosition/AddPositionModal.jsx
- src/components/Modals/ViewPosition/ViewPositionModal.jsx
> [feat-90] add more tooltips to icons

- src/components/Dashboard/List/List.jsx
- src/components/Dashboard/List/style.js
- src/contexts/MessagesContext.jsx
- Hover on position
- overflow in column
- remove some consoles,logs
> Bug fix marges bugs

- package-lock.json
- src/components/Dashboard/Homepage/Homepage.jsx
- src/components/Dashboard/List/List.jsx
- src/components/Dashboard/Navbar/Navbar.jsx
- src/components/Dashboard/SearchBar/SearchBar.jsx
- src/components/Input/Filter/FilterInput.jsx
> [Fix-51] - fix conflicts

- README.md
> [Doc-99] - Update README.md

- src/components/Auth/Login/Login.jsx
- src/components/Auth/Login/style.js
Design the page to be responsive
> [feat-53] design login page to be responsive

- src/components/Footer/Footer.jsx
Now the footer will be staying at the end of the application.
> [refactor-118] add styles to footer

- src/index.js
Added style to console log when lookes into devtool! 🥳 
Preview:
> [feat-113] add style to devtools console

- src/components/Input/style.js
- src/components/Modals/ViewPosition/DesTab/DesTabStyle.js
- src/components/Modals/ViewPosition/ViewPositionModal.jsx
- src/components/Modals/ViewPosition/ViewTab/viewTabStyle.js
- src/components/Modals/ViewPosition/style.js
Design the `edit & view modal` to be responsive to mobile.
> [feat-60+59] design responsive edit & view modal

- src/hooks/useKanban.jsx
> [bug-164] change orderBy value to date

- src/hooks/useKanban.jsx
fix the error `no document found` problem.
> [bug-170] fix no document error

- src/components/Auth/ForgotPassword/style.js
- src/components/Auth/Login/style.js
- src/components/Auth/Signup/style.js
- src/components/Dashboard/List/style.js
- src/components/Dashboard/SearchBar/style.js
- src/components/Dashboard/Sort/style.js
- src/components/Errors/BigError.jsx
- src/components/Footer/Footer.jsx
- src/components/Input/style.js
- src/components/LanguageDropDown/style.js
- src/components/Messages/style.js
- src/components/Modals/AddPosition/style.js
- src/components/Modals/ViewPosition/DesTab/DesTabStyle.js
- src/components/Modals/ViewPosition/ViewTab/viewTabStyle.js
- src/components/Modals/ViewPosition/style.js
- src/components/User/Profile/style.js
- src/components/User/UpdateProfile/style.js
- src/helpers/index.js
- src/styles/_color.js
- src/styles/index.js
add `styles/_color.js` file to organized all colors in one place.
> Feat 190 add color file palette

- public/index.html
- src/components/App.js
- src/components/Auth/ForgotPassword/ForgotPassword.jsx
- src/components/Auth/ForgotPassword/style.js
- src/components/Auth/Login/Login.jsx
- src/components/Auth/Login/style.js
- src/components/Auth/Signup/Signup.jsx
- src/components/Auth/Signup/style.js
- src/components/Footer/Footer.jsx
- src/components/Input/style.js
- src/components/LanguageDropDown/LanguageDropDown.jsx
- src/components/LanguageDropDown/style.js
- src/components/Navbar/GeneralNav/style.css
- src/styles/Global.style.css
1. Removed back button from login page
2. Refactor CSS for login-signup/forget password pages
3. Fixed language direction on login/signup/forget password pages
> [Fix-185] remove back button from login page

- src/components/Input/StatusInput.jsx
- src/components/Input/style.js
- src/components/Modals/AddPosition/AddPositionModal.jsx
- src/components/Modals/AddPosition/style.js
- src/components/Modals/ViewPosition/DesTab/DesTabStyle.js
- src/components/Modals/ViewPosition/ViewTab/viewTabStyle.js
- src/components/Modals/ViewPosition/style.js
> [Refactor-194]  dashboard modals translation direction

- src/components/User/Profile/Profile.jsx
- src/components/User/Profile/style.js
- src/components/User/UpdateProfile/UpdateProfile.jsx
- src/components/User/UpdateProfile/style.js
- src/styles/shared/formHeader.js
> [Refactor-192]user pages translation direction

- src/components/Dashboard/SearchBar/style.js
- src/components/Dashboard/Sort/style.js
- src/components/Language/Language.jsx
- src/components/Navbar/DashboardNav/DashboardNav.jsx
- src/components/Navbar/DashboardNav/style.js
> [Refactor-193] translation direction Dashboard

- App.tsx
- src/navigation/RootStackScreens.ts
- src/screens/ForgotPassword/Screens/PasswordScreen.tsx
- src/screens/ForgotPassword/Screens/handlers/password-handlers.tsx
- src/screens/ForgotPassword/Screens/types/passowrd.ts
- src/screens/ForgotPassword/stories/EmailScreen.stories.tsx
- src/screens/ForgotPassword/stories/PasswordScreen.stories.tsx
- src/shared/Input/Input.tsx
> SFE-35: Create forgot password - password screen
